### ISSUE TITLE
some improvement suggestion

### ISSUE THREAD

**Issue by homura** [zhangyouxin/demo-nexus#12]
It is better to 

- display the connected network (Nexus's network need to be determinable)
- have a guide to claim testnet token
- transfer limitation tip, minimal and maximal
- transfer all token

**Comment by zhangyouxin** [comment]
- [x] display the connected network (Nexus's network need to be determinable) #15 
- [x] have a guide to claim testnet token #16 
- [x] transfer limitation tip, minimal and maximal #17 
- [x] transfer all token #18
